### ISSUE TITLE
Invalid HTTP_HOST header

### ISSUE THREAD

**Issue by MohamedElashri** [Mathics3/mathics-omnibus#11]
Hello 

There is a problem with using the docker image on any public instance. You will get an error like that. 

```
Invalid HTTP_HOST header: '<ip>:8000'. You may need to add '<ip>' to ALLOWED_HOSTS.
Bad Request: /
```

I think you will need a way to specify `ALLOWED_HOSTS = ['*'] ` in Django `settings.py` by default if we are using docker.

**Comment by TiagoCavalcante** [comment]
@MohamedElashri how did you setup the instance?

**Comment by MohamedElashri** [comment]
> 

I did it via `docker-compose.yml`

```yml
version: '2'
services:
    mathics:
        container_name: mathics
        image: mathicsorg/mathics:latest
        volumes:
            - /home/docker/volumes/mathics/data:/usr/src/app/data
        ports:
            - "8000:8000"
```
